/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_theflyingfishgameapp_GameOverActivity_OnKeyListener */

#ifndef _Included_com_example_theflyingfishgameapp_GameOverActivity_OnKeyListener
#define _Included_com_example_theflyingfishgameapp_GameOverActivity_OnKeyListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
